import turtle
t = turtle.Turtle()
t.penup()
t.goto(0,120)
t.pendown()

for i in range(12):
    t.pencolor('black')
    t.fillcolor('yellow')
    t.begin_fill()
    t.left(60)
    t.fd(80)
    t.left(60)
    t.fd(80)
    t.left(120)
    t.fd(80)
    t.left(60)
    t.fd(80)
    t.left(60)
    t.end_fill()
    t.pencolor('red')
    t.circle(-120,30)
t.hideturtle()
turtle.done()